# Generated by Django 4.2.29 on 2026-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True, verbose_name='イベントID')),
                ('event_type', models.CharField(blank=True, max_length=64, verbose_name='イベント種別')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '処理済みWebhookイベント',
                'verbose_name_plural': '処理済みWebhookイベント',
            },
        ),
    ]
