# Generated by Django 4.2.29 on 2026-03-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('organizer_name', models.CharField(blank=True, max_length=200, verbose_name='主催者名')),
                ('organizer_email', models.EmailField(blank=True, max_length=254, verbose_name='主催者メール')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='公演名')),
                ('starts_at', models.DateTimeField(verbose_name='開演')),
                ('open_at', models.DateTimeField(verbose_name='開場')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='events.event', verbose_name='作品')),
            ],
            options={
                'verbose_name': '公演',
                'verbose_name_plural': '公演',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('front_row', '最前席'), ('front', '前方席'), ('center', '中央席'), ('rear', '後方席')], max_length=20, verbose_name='席種コード')),
                ('name', models.CharField(max_length=50, verbose_name='席種表示名')),
                ('capacity', models.PositiveIntegerField(verbose_name='定員')),
                ('price_card', models.PositiveIntegerField(verbose_name='カード決済価格')),
                ('price_cash', models.PositiveIntegerField(verbose_name='現金価格')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_tiers', to='events.performance', verbose_name='公演')),
            ],
            options={
                'verbose_name': '席種',
                'verbose_name_plural': '席種',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='seattier',
            constraint=models.UniqueConstraint(fields=('performance', 'code'), name='unique_tier_per_performance'),
        ),
    ]
