# Generated by Django 4.2.29 on 2026-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cast',
            field=models.TextField(blank=True, verbose_name='出演'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='会場住所'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='会場名'),
        ),
    ]
