# Generated by Django 4.2.29 on 2026-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cast_event_venue_address_event_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer_image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='フライヤー画像URL'),
        ),
    ]
