# Generated by Django 4.2.29 on 2026-04-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_flyer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seattier',
            name='price_card',
            field=models.PositiveIntegerField(verbose_name='前売り価格'),
        ),
        migrations.AlterField(
            model_name='seattier',
            name='price_cash',
            field=models.PositiveIntegerField(verbose_name='当日価格'),
        ),
    ]
