# Generated by Django 4.2.29 on 2026-04-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_performance_show_fanclub_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_signature',
            field=models.TextField(blank=True, verbose_name='メール署名'),
        ),
    ]
