# Generated by Django 4.2.29 on 2026-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_email_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattier',
            name='is_staff_only',
            field=models.BooleanField(default=False, help_text='True の席種は公開APIから除外され、スタッフ用画面のみで選択可能', verbose_name='スタッフ専用枠'),
        ),
        migrations.AlterField(
            model_name='seattier',
            name='code',
            field=models.CharField(choices=[('row_a', 'A列'), ('row_b', 'B列'), ('row_c', 'C列'), ('row_d_bench', 'D列ベンチシート'), ('row_e_bench', 'E列ベンチシート'), ('invite', '招待')], max_length=20, verbose_name='席種コード'),
        ),
    ]
