# Generated by Django 4.2.29 on 2026-04-23 12:07

from django.db import migrations, models


def migrate_invite_to_staff_seat(apps, schema_editor):
    """既存の code='invite' レコードを code='staff_seat' にリネームし、
    関係者席の仕様 (name='関係者席', price=4800) に揃える。
    """
    SeatTier = apps.get_model("events", "SeatTier")
    SeatTier.objects.filter(code="invite").update(
        code="staff_seat",
        name="関係者席",
        price_card=4800,
        price_cash=4800,
    )


def reverse_staff_seat_to_invite(apps, schema_editor):
    SeatTier = apps.get_model("events", "SeatTier")
    SeatTier.objects.filter(code="staff_seat").update(
        code="invite",
        name="招待",
        price_card=0,
        price_cash=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_seattier_is_staff_only_alter_seattier_code'),
    ]

    operations = [
        # 先に既存データをリネーム（choices 変更の前に実施）
        migrations.RunPython(
            migrate_invite_to_staff_seat,
            reverse_staff_seat_to_invite,
        ),
        migrations.AlterField(
            model_name='seattier',
            name='code',
            field=models.CharField(choices=[('row_a', 'A列'), ('row_b', 'B列'), ('row_c', 'C列'), ('row_d_bench', 'D列ベンチシート'), ('row_e_bench', 'E列ベンチシート'), ('staff_seat', '関係者席')], max_length=20, verbose_name='席種コード'),
        ),
    ]
