# Generated by Django 4.2.29 on 2026-03-30 05:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='枚数')),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='確認トークン')),
                ('guest_name', models.CharField(max_length=200, verbose_name='氏名')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='メール')),
                ('guest_phone', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('reservation_type', models.CharField(choices=[('card', 'カード決済'), ('cash', '現金'), ('invite', '招待')], max_length=10, verbose_name='予約種別')),
                ('status', models.CharField(choices=[('pending', '仮予約'), ('confirmed', '確定'), ('cancelled', 'キャンセル')], default='pending', max_length=10, verbose_name='ステータス')),
                ('payment_status', models.CharField(choices=[('unpaid', '未払い'), ('paid', '支払い済み'), ('refunded', '返金済み')], default='unpaid', max_length=10, verbose_name='支払状態')),
                ('checked_in', models.BooleanField(default=False, verbose_name='入場済み')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='入場日時')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Session ID')),
                ('pre_sale_type', models.CharField(blank=True, max_length=50, verbose_name='先行種別')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.performance', verbose_name='公演')),
                ('seat_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.seattier', verbose_name='席種')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-created_at'],
            },
        ),
    ]
