# Generated by Django 4.2.29 on 2026-03-30 05:19

from django.db import migrations, models
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='token',
            field=models.CharField(default=reservations.models._generate_token, editable=False, max_length=32, unique=True, verbose_name='確認トークン'),
        ),
    ]
