# Generated by Django 4.2.29 on 2026-04-13 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_flyer_image_url'),
        ('reservations', '0002_alter_reservation_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(blank=True, choices=[('card', 'カード決済'), ('cash', '現金'), ('invite', '招待')], default='', max_length=10, verbose_name='予約種別'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.seattier', verbose_name='席種'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('draft', '仮受付'), ('pending', '仮予約'), ('confirmed', '確定'), ('cancelled', 'キャンセル')], default='pending', max_length=10, verbose_name='ステータス'),
        ),
    ]
