# Generated by Django 4.2.29 on 2026-04-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_public_entry_enabled'),
        ('reservations', '0011_accesslink_header_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allow_any_seat',
            field=models.BooleanField(default=False, verbose_name='どの席でも可'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_choice_seat_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.seattier', verbose_name='第一希望席'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='second_choice_seat_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.seattier', verbose_name='第二希望席'),
        ),
    ]
